---
title: "Take-home Exercise 3"
description: |
  A new article created using the Distill format.
author:
  - name: Chu Yi Ning 
    url: https://www.linkedin.com/public-profile/settings?trk=d_flagship3_profile_self_view_public_profile
    affiliation: SMU SCIS
    affiliation_url: https://scis.smu.edu.sg/
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview

# Getting Started

```{r}
packages = c('tidyverse', 'patchwork', 'dplyr', 'lubridate')
for(p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}
```


## Data Cleaning

```{r}
data <- read_csv("data/FinancialJournal.csv")
dim(data)
```
### Order by Participant ID
```{r}
data_orderBypart <- data[order(data$participantId),]
```


We can see there are some duplicates for Shelter and Education.


```{r, echo=FALSE}
head(data_orderBypart, 5)
```


distinct function in dplyr will be used to remove duplicates

```{r}
data_clean <- data %>% distinct(participantId, timestamp, category, amount,
                   .keep_all = TRUE)
head(data_clean, 10)
dim(data_clean)
```

There are 1113 duplicates in total.

### Add a new column Month which extract month from timestamp
```{r}
data_clean['month'] <- month(data_clean$timestamp)
```

```{r, echo = FALSE}
head(data_clean, 5)
```




