---
title: "In-class Exercise 4"
description: |
  
author:
  - name: Chu Yi Ning 
    url: https://www.linkedin.com/public-profile/settings?trk=d_flagship3_profile_self_view_public_profile
    affiliation: SMU SCIS
    affiliation_url: https://scis.smu.edu.sg/
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      eval = TRUE, 
                      message = FALSE, 
                      warning  = FALSE, 
                      fig.retina = 3)
```

# Getting Started 

## Setting up R packages

To start with, [ggstatsplot](https://indrajeetpatil.github.io/ggstatsplot/) and tidyverse packages will be launched using library().


```{r}
packages = c('ggstatsplot','tidyverse')
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
}
```


## Importing Data

```{r}
exam <- read_csv("data/Exam_data.csv")
```


## Working with ggstatsplot

### ANOVA test

```{r, fig.height = 6}
set.seed(5)

ggbetweenstats(
  data = exam,
  x = RACE, 
  y = ENGLISH,
  type = "bayes"
)
```

